# Generated by Django 4.0.4 on 2022-04-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_post_rasm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('img', models.ImageField(upload_to='')),
                ('isRead', models.BooleanField(default=False)),
                ('sendTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
